### ISSUE TITLE
Problem with sync for audio streams

### ISSUE THREAD

**Issue by alin** [kolyvan/kxmovie#1]
This video for example has problems (both network streaming and locally saved) - the meta info seems to be accurate - the same as in ffplay where it plays OK: http://cds1.yospace.com/access/d/u/0/1/web/type=video,fmt=any,minq=0,maxq=100000000,mins=1x1,maxs=640x608,minr=5,maxr=100,/50602731?f=100312513718\

**Comment by kolyvan** [comment]
Hm, I can't see any video by link. 
Server returned a response 'Internal error'.

**Comment by alin** [comment]
Sorry, it had an extra backslash in it http://cds1.yospace.com/access/d/u/0/1/web/type=video,fmt=any,minq=0,maxq=100000000,mins=1x1,maxs=640x608,minr=5,maxr=100,/50602731?f=100312513718

I'm not sure if the audio codec has troubles or the app itself, if I extract the mp3 stream in a separate file with the same specs and put it in the app it works fine

**Comment by kolyvan** [comment]
Thanks for your bug report.
It seems I fixed it. 
The problem was in incorrect handling of mono audio streams.

**Comment by alin** [comment]
I found the cause, because the audio stream is mono the checks detect it to be unsupported by the codec, so it is resampled. If I force the the outputchannels to 1 it works for this case. Will continue investigate :)
