### ISSUE TITLE
H264 lag

### ISSUE THREAD

**Issue by tonywonghs** [kolyvan/kxmovie#10]
Great work.

I managed to have it working fine with flv, mov, mp4 and with f4v that not in your list. But feel lag for video with H264, tested with both remote and local H264, on iPhone 4 with iOS 6. Any clue? Thanks!

**Comment by kolyvan** [comment]
HI, Can you give me more info about video format (like bitrate, frame resolution), please?
You may get such data from the info view or from the output log.
Thanks.

**Comment by nokai** [comment]
A few seconds and lag rtmp://aragontvlivefs.fplive.net/aragontvlive-live/stream_normal_abt
& more rtmp://ucaster.eu:1935/live/_definst_/discoverylacajatv

**Comment by kolyvan** [comment]
Yes, sometimes it lags due to network latency.
The fast and crude way to fix it's to change NETWORK_BUFFERED_DURATION parameter.
Set it to 3.0 or 4.0.
The right way it's to change the buffering algorithm for remote files.
I have this issue in my TODO list, but I can't say anything about timeline.

Best wishes.

**Comment by nokai** [comment]
Ok, thanks, I'll try

**Comment by nokai** [comment]
I have been trying to change the NETWORK_BUFFERED_DURATION but does not fix the lag and does not work

Wait your updates.

Thanks

**Comment by sharp** [comment]
iPhone 4s and iPhone 5 is ok for me  :)

**Comment by nokai** [comment]
I've tried these two directions\* .... with an ipad2, iphone4 and iphone5 and works much lag, stutters.

*
rtmp://aragontvlivefs.fplive.net/aragontvlive-live/stream_normal_abt
rtmp://ucaster.eu:1935/live/_definst_/discoverylacajatv

You have changed anything?

**Comment by itkingdom** [comment]
Hi,

I tried your streams:
rtmp://ucaster.eu:1935/live/_definst_/discoverylacajatv
it's OK ok for me. 
I think you first try on your PC to confirm you internet connection is fast enough

**Comment by itkingdom** [comment]
Could anyone try this stream: http://livecdn.megatv.vn/live/VTV3_Cluster_out
The first 15sec is very smooth, after then, lag & stutter : (

My definition
#define NETWORK_BUFFERED_DURATION 4.0

**Comment by sharp** [comment]
http://livecdn.megatv.vn/live/VTV3_Cluster_out is ok for me , I have watched half an hour :P

**Comment by itkingdom** [comment]
Cool! May be internet speed issue, like what @nokai had :-D

**Comment by itkingdom** [comment]
By the way, what is your NETWORK_BUFFERED_DURATION value?

**Comment by sharp** [comment]
I didn't modify anything , I think you can ping your server to check network is ok.

```
#define DEFAULT_DECODE_DURATION   0.1
#define NETWORK_BUFFERED_DURATION 2.0
```

To @kolyvan 

I hope one feature : It will be good to add reload url api for KxMovieViewController, so I can reload the url to replay if there are some errors when live streaming

**Comment by nokai** [comment]
The problem is with ffmpeg

I try with rtmp://ucaster.eu:1935/live/_definst_/discoverylacajatv

```
#define DEFAULT_DECODE_DURATION   0.1
#define NETWORK_BUFFERED_DURATION 4.0
```

in simulator and works well.

but on the iphone 4 with wifi, the same connection (very good). lag imagen & audio

```
2012-12-27 16:32:39.099 KxMovieExample[3483:6503] desync audio (lags) skip 2.0520 0.0260
```

in iphone 5

```
2012-12-27 16:39:38.055 KxMovieExample[3231:6903] desync audio (lags) skip 73.7990 71.7890
```

:(

**Comment by itkingdom** [comment]
I think it's buffering issue, not ffmpeg : ) @kolyvan  may give us some ideas how to solve

**Comment by kolyvan** [comment]
Hi All, 

I pushed the commit https://github.com/kolyvan/kxmovie/commit/0ba37a3f773c2114b2485cbcae3107e14d54c408 to new branch  'network'.
There are small improvements of buffering network-based streams.
Certainly it cannot solve bandwidth issue, but buffering process will a little more clear for user.

Thanks all for feedback.
