### ISSUE TITLE
An error when I try to connect to a rtsp://192.168.1.xx/ch00_0 like stream

### ISSUE THREAD

**Issue by rollpard** [kolyvan/kxmovie#11]
When I run this program both on sim or my iPad2, the console tell me:

[h264 @ 0x9a88a00] Missing reference picture
[h264 @ 0x9a88a00] decode_slice_header error
[h264 @ 0x9a88a00] concealing 330 DC, 330 AC, 330 MV errors in P frame
[h264 @ 0x9a46a00] Width/height/bit depth/chroma idc changing with threads is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.

How can I solve this problem?

**Comment by kolyvan** [comment]
Hi, But it's obvious. See your log.

>  Update your FFmpeg version to the newest one from Git

Type in console:

```
cd kxmovie
git submodule foreach git pull
```

or

```
cd kxmovie/ffmpeg
git pull
```

Best wishes

**Comment by rollpard** [comment]
thanks,but
Am I using the lastest FFMPEG version by typing
"git submodule update --init"?
:)
maybe the newest ffmpeg has some issue with this feature?

**Comment by sharp** [comment]
You can goto FFMPEG folder and run `git tag` and`git checkout sometag` ,  the latest tag works for me.
