### ISSUE TITLE
Audio of local .wmv movie delayed and lagging after start 

### ISSUE THREAD

**Issue by neowinston** [kolyvan/kxmovie#12]
Hi Konstantin Boukreev,

Again, thank you very much for your great project!!!

I'm experiencing a considerable delay for the audio to start on a local .wmv movie. On the computer it plays nicely, but on my iPhone 4S, with iOS 6.0, after a delay to start the audio keeps lagging.

The same results happen when I scrub back or forward.

Could you please check this out? Here is the link for the video, so you can download it and try for yourself:

http://sdrv.ms/UQJPSu

Thank you!

**Comment by kolyvan** [comment]
Hi,

Hm, very interesting problem.
Thanks, for sharing this with me )

Audio packets have a delay of about 3-4 seconds. 
I am unsure, is it typical behaviour of wmv format or not?

By the way, I found the solution, but unfortunately it's not optimal way.

You need to change DEFAULT_DECODE_DURATION and NETWORK_BUFFERED_DURATION constants in KxMovieViewController.m.
For example, set it to 5 or 6 seconds.

I tested and seems to me, this solves the issue with audio lags.

And beware, the resampling code in kxMovieDecoder in case of wmv audio is not ideal. 
I plan to fix it, but don't know when.

Best wishes.

**Comment by neowinston** [comment]
I've noticed this behavior only with local .wmv, and changing the  DEFAULT_DECODE_DURATION and NETWORK_BUFFERED_DURATION to 6 seconds solves the lagging problem, though the delay after scrubbing back or forward persists. 

Thank you very much for your quick reply and I do appreciate your investigation of the causes for this problem.

Regards
