### ISSUE TITLE
Can I copy kxmovie folder to my project ?

### ISSUE THREAD

**Issue by sharp** [kolyvan/kxmovie#13]
When I modify some UI for kxmovie player, I need to run `rake build_movie` and copy the output folder, that is a little troublesome.

Can I modify the kxmovie code in my project and it will be built by xcode automatically ？

**Comment by kolyvan** [comment]
Yes, certainly you can.
Look at https://github.com/kolyvan/kxtorrent project as sample using kxmovie as subproject.

Best wishes.

**Comment by sharp** [comment]
Nice, thank you for your perfect project!
