### ISSUE TITLE
rake  failure

### ISSUE THREAD

**Issue by juvham** [kolyvan/kxmovie#130]
when i run the rake some error ;
$ rake
Executing cd FFmpeg; ./configure --disable-ffmpeg --disable-ffplay --disable-ffserver --disable-ffprobe --disable-doc --disable-bzlib --target-os=darwin --enable-cross-compile --enable-version3 --arch=arm --cpu=cortex-a8 --enable-pic --extra-cflags='-arch armv7 -miphoneos-version-min=6.0' --extra-ldflags='-arch armv7 -miphoneos-version-min=6.0' --extra-cflags='-mfpu=neon -mfloat-abi=softfp' --enable-neon --enable-optimizations --disable-debug --disable-armv5te --disable-armv6 --disable-armv6t2 --enable-small --cc=/Applications/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk 
/Applications/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
rake aborted!
*******\* Build failed ********
/Users/XUNNIU/Desktop/github/kxmovie/Rakefile:8:in `system_or_exit'
/Users/XUNNIU/Desktop/github/kxmovie/Rakefile:159:in`buildArch'
/Users/XUNNIU/Desktop/github/kxmovie/Rakefile:207:in `block in <top (required)>'
Tasks: TOP => default => build_ffmpeg => build_ffmpeg_armv7
(See full trace by running task with --trace)

**Comment by xiangyu-sun** [comment]
change rake file's SDK version to your Xcode SDK version

**Comment by phucnm** [comment]
First of all, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/developer/SDKs/ to find out what SDKs are existed in your OS

Then modify SDK_VERSION to your proper value, ex SDK_VERSION='9.2'

**Comment by leon790** [comment]
cd kxmovie
then: nano Rakefile
then: change line 13 : SDK_VERSION='7.0' to SDK_VERSION='9.3'(or your SDK version)
and change too line 16: GCC_PATH='/Applications/XCode.app/Contents/Developer/Toolchains/ to GCC_PATH='/Applications/Xcode.app/Contents/Developer/Toolchains/
then press control + o to save and press enter, then control + x and then rake again

tell me if works =)

**Comment by juvham** [comment]
thank’s  it's works
