### ISSUE TITLE
Stuttering playback with 1080i mpeg2ts file

### ISSUE THREAD

**Issue by matzr** [kolyvan/kxmovie#15]
Hi Konstantin,

I have been trying to get a file encoded in 1440x1080 playing on iPad2 / iPad3 / iPhone4 using your KxMoviePlayer, but no matter if it was local or streamed, the playback was stuttering.

I could not really figure out anything to make it work properly. It looks like it's almost maxing out the CPU use (I checked using Instruments profiling tools). Maybe there is a way to optimise this (either the decoder itself, or ffmpeg code, or else changing some compile time switches) to make it work, but I must admit I don't really know in which direction to investigate.

I was wondering if maybe you had an idea of what could be done in order to be able to play such files. I uploaded a sample file for you to have a look when you have a minute: http://www.sendspace.com/file/y1ioim   

Best Regards,

**Comment by kolyvan** [comment]
Just tested in on iPad 4.
In fact the problem in latest addition of  avpicture_deinterlace. (
Try to comment it and will see difference.

**Comment by matzr** [comment]
Hi Konstantin,

I am going to test that straight away...
Mmmm, I might try to come up with a mechanism to evaluate how powerful the
device is, what the decoded resolution is and enable/disable deinterlacing
conditionally, then. It should be possible.
I will run some tests with lower end devices after that: iPad 2 / iPad 1
and see how they behave in regards to performance.
Again thank you for this amazing work.
Keep up the good work. I'll keep you updated to let you know how all this
goes.

Cheers,

Mathieu

**Comment by matzr** [comment]
A bit more details about this perf issue. 
It runs indeed fine without deinterlacing (even though it doesn't look great because of this line effect) on an iPhone 5 (A6 proc = 1.3 GHz Dual Core ARMv7s).
However, any device below these specs (that includes all iPad 1/2/3, iPhone 3/3gs/4/4s and all iPod to date) cannot playback these videos correctly, i.e. it stutters.

I have tried different compile flags for ffmpeg (especially enabling FPU through "--extra-cflags='-arch armv7 -mfpu=neon'") but it did not make any difference.

Now I am wondering how this can be achieved, given that I can play the same video file in other media players that seem to be using ffmpeg (iMediaPlayer for instance, which is available on the AppStore).

**Comment by kolyvan** [comment]
See 50cbe99f13f8646055c8327b8bad7bee13c7c690 commit.
After build ffmpeg with neon support, the average performance increases about 30% for mpeg2 1440x1080 with enabled deinterlacing.
It almost enough for iPad 4. 
But it's still unable to play this HD movie on iPhone 4S without stuttering.
