### ISSUE TITLE
yuvj420p stream cannot be viewed

### ISSUE THREAD

**Issue by kristopherjohnson** [kolyvan/kxmovie#23]
I am trying to view the output of an Axis P5512-E Network Camera. It provides an RTSP H.264 output stream with yuvj420p format. This stream is viewable in VLC, QuickTime, and other multimedia viewers.

Unfortunately, it doesn't look like kxmovie supports the yuvj420p format. When I try to connect to that stream, the app simply displays the spinning wheel until the app eventually exits.

The KxMovieDecoder class contains this code:

```
- (BOOL) setupVideoFrameFormat: (KxVideoFrameFormat) format
{
    if (format == KxVideoFrameFormatYUV &&
        _videoCodecCtx &&
        _videoCodecCtx->pix_fmt == AV_PIX_FMT_YUV420P) {

        _videoFrameFormat = KxVideoFrameFormatYUV;
        return YES;
    }

    _videoFrameFormat = KxVideoFrameFormatRGB;
    return _videoFrameFormat == format;
}
```

This does not properly handle the case where `format` is `KxVideoFormatYUV` and `_videoCodecCtr->pix_fmt` is `AV_PIX_FMT_YUVJ420P`. It sets `_videoFrameFormat` to `KxVideoFrameFormatRGB`, and then `-[KxMovieGLView initWithFrame:decoder:]` creates a `KxMovieGLRenderer_RGB`.

I have hacked the code to force it to create a `KxMovieGLRenderer_YUV`, but I still see only a spinning wheel when I run the app, so I assume some changes to the renderer are needed to support yuvj420p.

**Comment by kristopherjohnson** [comment]
It looks like this change might fix the problem with processing of yuvj420p:

```
- (BOOL) setupVideoFrameFormat: (KxVideoFrameFormat) format
{
    if (format == KxVideoFrameFormatYUV &&
        _videoCodecCtx &&
        (_videoCodecCtx->pix_fmt == AV_PIX_FMT_YUV420P || _videoCodecCtx->pix_fmt == AV_PIX_FMT_YUVJ420P)) {

        _videoFrameFormat = KxVideoFrameFormatYUV;
        return YES;
    }

    _videoFrameFormat = KxVideoFrameFormatRGB;
    return _videoFrameFormat == format;
}
```

Unfortunately, the sample still doesn't work with the Axis camera, but that is apparently due to a framerate issue. `frame.duration` gets set to zero (because av_frame_get_pkt_duration() always returns zero)), so the app thinks time does not pass and never renders a frame. If I hack it to force it to render a frame when a frame is available, then that frame is displayed properly, so I think the YUV frame decoding is working. Now I just have to figure out the framerate timing.

**Comment by kolyvan** [comment]
Hi,

Take a look at new branch juvj420p https://github.com/kolyvan/kxmovie/tree/yuvj420p
I added a fix for zero-length frames like you got from web-camera.
And also there is your fix for yuvj420p streams from comment above.

Best wishes.

**Comment by kristopherjohnson** [comment]
Thanks! That's working pretty well.

My only complaint is that the video displays for a few seconds at a time, then the spinning wheel appears for a couple of seconds while the HUD says "buffering", and then the video displays again, and this cycle keeps going. I'll look at the code, and also check whether the camera is actually generating a continuous stream, but do you know an easy way to get a continuous display without the buffering pauses?

**Comment by itkingdom** [comment]
The buffering issues are also happened while I'm trying 1080p stream. I think we need a new way to handle buffer ^^

**Comment by kolyvan** [comment]
See commit bc398e21f9d57a149204f079aa82fb99c02fb392 
I added ability to completely disable buffering via setting KxMovieParameterMinBufferedDuration parameter to zero.

```
parameters[KxMovieParameterMinBufferedDuration] = @(0.0f);
```

For testing, uncomment line 212 in KxMovieExample/MainViewController.m and play your rtsp stream.

**Comment by kristopherjohnson** [comment]
That's working perfectly.

Thank you for all your assistance.

**Comment by kolyvan** [comment]
Thank you for your contribution in project.
I merged branch yuvj420p into master.
