### ISSUE TITLE
Customization of KxMovieViewController

### ISSUE THREAD

**Issue by kristopherjohnson** [kolyvan/kxmovie#24]
This is not really an "issue"; it's more of a Request for Comments for doing some re-architecting of the kxmovie library.

For an app I'm developing, I need to display video like KxMovieViewController does now, but I need some different functionality:
- I want to remove the existing controls (HUDs, sliders, etc), because I am displaying a live video feed rather than one that can be fast-forwarded/rewound/etc.
- I want to add some buttons that can be used to pan/tilt/zoom the camera.
- I want to add some gesture recognizers

The quick-and-dirty way to do this would be to just copy KxMovieViewController and rip out the parts I don't need. However, I wonder whether anyone has given thought to a generic way to customize the viewer.

I'm thinking about creating some sort of "base video controller" that provides the basic functionality (setting up the GL view, decoding frames, pause, play, etc.), and then KxMovieViewController would be a subclass that had the controls, but other people could create other subclasses that have different controls but share the basic implementation.

Does this make sense? Does anyone have different ideas?

**Comment by sharp** [comment]
Good issue , I have overrided the KxMovieViewController myself

**Comment by kristopherjohnson** [comment]
Another thought: A lot of what KxMovieViewController does is deal with opening the stream and and retrieving frames. It might be useful to factor that functionality out into a separate class ("KxMovieStreamingEngine"?), to both simplify the view controller code and to make it possible to do things with video streams that don't require a view controller (recording video to a file, for example).

**Comment by kolyvan** [comment]
Going this way at end of  the road we will have: KxMovieFactory and KxMovieFactoryFactory )

**Comment by kristopherjohnson** [comment]
I'm going to close this issue. I have my own application-specific refactoring of the KxMovie stuff, but it would take a bit of work to make it useful for everyone, and my customer isn't going to pay for that.

**Comment by timeview-activu** [comment]
Would be nice if we have gotten more info on how best to override and/or Customization Kx
