### ISSUE TITLE
Rake dosent work

### ISSUE THREAD

**Issue by TBSystem** [kolyvan/kxmovie#25]
hi when i run the rake, its says that the --disable armvfp command dosent exist 

can you help me out :)
From terminal:
Unknown option "--disable-armvfp".
See ./configure --help for available options.
rake aborted!
*******\* Build failed ********

**Comment by kolyvan** [comment]
Hi,

Sorry, but I unable to reproduce such error.
I checked the build instruction just in case and builded kxmovie from scratch.

```
git clone git://github.com/kolyvan/kxmovie.git
cd kxmovie
git submodule update --init 
rake
```

and didn't observe any problem.

Perhaps, are you using an unsupported version of ffmpeg?

Best wishes.

**Comment by sharp** [comment]
I think you did not get the correct ffmpeg version.

**Comment by kristopherjohnson** [comment]
FWIW, I've been doing a lot of building of kxmovie and FFmpeg over the past week, and haven't had any problems.

It might help if you provide this information:
- Xcode version
- Contents of FFmpeg/config.log (if any)

**Comment by ghost** [comment]
It seems that the option --disable-armvfp has been renamed to --disable-vfp in the latest src of FFmpeg. Are you fetching FFmpeg from a specific branch or tag in the kxmovie project?

**Comment by kristopherjohnson** [comment]
kxmovie currently uses commit `d312ffdd79bd22b5a051790c993eda6b1366cdfc` for its FFmpeg submodule, which is from October 2012 (I think).

I've built with a newer version of FFmpeg by doing the following:

```
cd kxmovie/FFmpeg
git checkout release/1.1
cd ..
vi Rakefile          # Change both instances of --disable-armvfp to --disable-vfp
rake
```

This does build new FFmpeg libraries.

Unfortunately, when I try to build the KxMovieExample target, I get linker errors. I can get it to run in the iOS Simulator by adding libiconv.dylib. But trying to build for device gives me this error:

```
Ld /Users/kdj/Library/Developer/Xcode/DerivedData/kxmovie-arodpbizpjyhwlcojwsjwswurwpa/Build/Products/Debug-iphoneos/KxMovieExample.app/KxMovieExample normal armv7
cd /Users/kdj/work/kxmovie
setenv IPHONEOS_DEPLOYMENT_TARGET 5.1
setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -L/Users/kdj/Library/Developer/Xcode/DerivedData/kxmovie-arodpbizpjyhwlcojwsjwswurwpa/Build/Products/Debug-iphoneos -L/Users/kdj/work/kxmovie/libs -F/Users/kdj/Library/Developer/Xcode/DerivedData/kxmovie-arodpbizpjyhwlcojwsjwswurwpa/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -filelist /Users/kdj/Library/Developer/Xcode/DerivedData/kxmovie-arodpbizpjyhwlcojwsjwswurwpa/Build/Intermediates/kxmovie.build/Debug-iphoneos/KxMovieExample.build/Objects-normal/armv7/KxMovieExample.LinkFileList -dead_strip -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=5.1 -lz -lavcodec -lavformat -lavutil -lswresample -lswscale -framework UIKit -framework Foundation -framework CoreGraphics -framework MediaPlayer -framework CoreAudio -framework AudioToolbox -framework Accelerate -framework QuartzCore -framework OpenGLES -o /Users/kdj/Library/Developer/Xcode/DerivedData/kxmovie-arodpbizpjyhwlcojwsjwswurwpa/Build/Products/Debug-iphoneos/KxMovieExample.app/KxMovieExample

ld: in /Users/kdj/work/kxmovie/libs/libavcodec.a(fft_fixed_neon.o), in section __TEXT,__text reloc 4: R_ABS reloc but no absolute symbol at target address for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no clue what this means.

According to a comment in http://www.tangentsoftworks.com/blog/2012/11/12/how-to-prepare-your-mac-for-ios-development-with-ffmpeg-libraries/, the solution is to use a new version of gas-preprocessor.pl found at https://github.com/mansr/gas-preprocessor. So I'll give that a whirl.

**Comment by kristopherjohnson** [comment]
OK, I have a branch ffmpeg-release/1.1 in my fork of kxmovie which builds and seems to work: https://github.com/kristopherjohnson/kxmovie/compare/ffmpeg-release;1.1

I'm going to test this with my own apps before making a formal pull request.
