### ISSUE TITLE
H264, AVI format play with lag & stutter.

### ISSUE THREAD

**Issue by ethosholic** [kolyvan/kxmovie#27]
Could anyone try this stream: http://dl.dropbox.com/u/36390277/blackbox.avi
lag & stutter : (
I tried play it in local.

FFmpeg has compiled with config.sh (http://dl.dropbox.com/u/36390277/config.sh)

Development environment
XCode 4.6
SDK iOS 6.1

Thank you.

**Comment by kolyvan** [comment]
Hi,

IMHO bitrate 6mb/s is too complex for iphone. 

I may suggest two methods:
- you may disable buffering for local stream
  
  parameters[KxMovieParameterDecodeDuration] = @(0.0f);
  parameters[KxMovieParameterMinBufferedDuration] = @(0.0f);

then, lags will still here but less noticeable
- or you may upgrade ffmpeg to latest release (v1.1), kxmovie uses a bit obsolete version of ffmpeg 0.8 and swithing to the latest version may help. 

Best wishes

**Comment by ethosholic** [comment]
Thank you for your solution.

When disable buffering for local stream with option you mentioned, playing with no buffering.
but fps is 5 or 6, play slowly.

Nothing to change my problem even if upgrade to latest release (v1.1).

Thank you.
