### ISSUE TITLE
Received memory warning.

### ISSUE THREAD

**Issue by jovisayhehe** [kolyvan/kxmovie#28]
I try to play this 720p video http://edge.v.iask.com/97811058.hlvKID=sina,viask&Expires=1361894400&ssig=xA3elVHv0a

it will be crash 

log：
KxMovieExample[1013:907] Received memory warning.

**Comment by kolyvan** [comment]
Sorry, but I can't test the link due to 'unable resolve hostname edge.v.iask.com'. 
Maybe You may provide another link ?

**Comment by jovisayhehe** [comment]
http://xhmikosr.1f0.de/samples/Big_Buck_Bunny/Big_Buck_Bunny_720p_x264.mkv
https://www.dropbox.com/s/61p7lpvseoix9tj/97811058.flv（need to downlod）

sorry ，i can't find a better hotlink website

**Comment by kolyvan** [comment]
HI,

Just checked video. 
The memory usage of buffered video frames  is about 100mb.
The solution is pretty simple, for such big movies you need set the minBufferedDuration parameter to 1 or 2 seconds.

```
parameters[KxMovieParameterMinBufferedDuration] = @(1.0f);
```

Perhaps there are need some code for automatic reduction of the buffer size for such big movies.
But I still unsure in usefulness this idea.

Best wishes.
