### ISSUE TITLE
How keep audio playing with app in background?

### ISSUE THREAD

**Issue by danieleratti** [kolyvan/kxmovie#29]
This is fantastic! But how can i keep audio playing when app goes in background?
Thanks

**Comment by kolyvan** [comment]
Hi,

If you want to keep playing in background, you need a little hack of source code.

The easy way is to remove line 467 with  [self pause]  in  [KxMovieViewController applicationWillResignActive:] method.

Also you may modify presentVideoFrame: method and disable the rendering in background.

Best wishes.

**Comment by viperfx** [comment]
@kolyvan if I was making an audio only app, that plays audio in the background and has no need for video or artwork. Could you suggest any improvements and optimisations in the code I could make please? What methods are not necessary?
