### ISSUE TITLE
Does  kxmovie support mpga audio ?

### ISSUE THREAD

**Issue by sharp** [kolyvan/kxmovie#3]
Hi, kolyvan 

Does  kxmovie support mpga audio ?

I can play h264video and mpga audio by VLC, but I can not play by kxmovie

![example image](http://i.imgur.com/ghpzu.png)

**Comment by jinan829** [comment]
Hello, Sharpx
I created the one issue which i am getting and pasted the link error.
I don't know why it doesn't work.
Could you please help me for it?
Best Regards.

**Comment by kolyvan** [comment]
> Does kxmovie support mpga audio ?

kxmovie is based on ffmpeg library, so it supports any ffmpeg supported format 
Isn't mpga file is just mp3 with another file extension, right? 
So I think kxmove may play mpga files.
