### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by gdier** [kolyvan/kxmovie#31]
There is an error when I'm linking kxmovie with
ffmpeg1.1.3(from http://ffmpeg.org/releases/ffmpeg-1.1.3.tar.gz)
xcode4.6, iOS6.1 SDK

Anyone has the same problem?

anyway, kxmovie is a great project for study video player programming, thanks.

---

Ld /Users/gdier/Library/Developer/Xcode/DerivedData/kxmovie-bwjlvssbuxmvekeokeoevpsoyjwj/Build/Products/Debug-iphoneos/KxMovieExample.app/KxMovieExample normal armv7
    cd /Users/gdier/code/kxmovie
    setenv IPHONEOS_DEPLOYMENT_TARGET 5.1
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -L/Users/gdier/Library/Developer/Xcode/DerivedData/kxmovie-bwjlvssbuxmvekeokeoevpsoyjwj/Build/Products/Debug-iphoneos -L/Users/gdier/code/kxmovie/libs -F/Users/gdier/Library/Developer/Xcode/DerivedData/kxmovie-bwjlvssbuxmvekeokeoevpsoyjwj/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -filelist /Users/gdier/Library/Developer/Xcode/DerivedData/kxmovie-bwjlvssbuxmvekeokeoevpsoyjwj/Build/Intermediates/kxmovie.build/Debug-iphoneos/KxMovieExample.build/Objects-normal/armv7/KxMovieExample.LinkFileList -dead_strip -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=5.1 -framework OpenGLES -framework QuartzCore -framework Accelerate -framework AudioToolbox -framework CoreAudio -framework MediaPlayer -framework CoreGraphics -framework Foundation -framework UIKit -lz -lavcodec -lavformat -lavutil -lswresample -lswscale -o /Users/gdier/Library/Developer/Xcode/DerivedData/kxmovie-bwjlvssbuxmvekeokeoevpsoyjwj/Build/Products/Debug-iphoneos/KxMovieExample.app/KxMovieExample

ld: in /Users/gdier/code/kxmovie/libs/libavcodec.a(fft_fixed_neon.o), in section __TEXT,__text reloc 4: R_ABS reloc but no absolute symbol at target address for architecture armv7

**Comment by kolyvan** [comment]
see discussion here: #30

**Comment by ghost** [comment]
still i am getting "R_ABS reloc" issue after copying new gasprocessor. please help me
