### ISSUE TITLE
memory leak ?

### ISSUE THREAD

**Issue by sharp** [kolyvan/kxmovie#33]
Hi, I profile my application when play mpegts stream , I fount that the memory is growing when I open player, so need to release player when close ? 
`KxMovieViewController *player = [KxMovieViewController movieViewControllerWithContentPath:path parameters:nil];
`
![ 2013-03-07 10 10 29](https://f.cloud.github.com/assets/121051/230663/00cad054-86cd-11e2-90cb-0320313e57cf.png)

**Comment by sharp** [comment]
BTW: My project is not ARC support .

**Comment by kolyvan** [comment]
> BTW: My project is not ARC support .

IMHO,  this is the answer.

Just in case I ran some profiling for check memory leakage and didn't found nothing.
