### ISSUE TITLE
Close a stream

### ISSUE THREAD

**Issue by aleufms** [kolyvan/kxmovie#37]
How can I close a failed stream? When we try to open a invalid stream, the decoder stuck, and is not allowed for us open other stream. When we try to open we I got this error:

"bind failed: Address already in use" and decoder returns with error: "Unable to open file"

There's no timeout. It waits until make a connection, and from there we can close the stream.

**Comment by kolyvan** [comment]
> , the decoder stuck, and is not allowed for us open other stream.

Interesting, will the commit 36c3f080b12c0c4d42511ce28315456a856a9c69 fix it?

**Comment by aleufms** [comment]
Hey, thank you for the update. When I update kxmovie I got an error trying to run it in simulator:
Undefined symbols for architecture i386:
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_close", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_open", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And an error when try to run in a actual device:
libavcodec.a(fft_fixed_neon.o), in section __TEXT,__text reloc 4: R_ABS reloc but no absolute symbol at target address for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aleufms** [comment]
I clone kxmovie in a new directory and it worked in simulator, but the error persists on actual device.

**Comment by kristopherjohnson** [comment]
Try the new gas-preprocessor.pl found at https://github.com/mansr/gas-preprocessor

**Comment by aleufms** [comment]
I'm using the gas-preprocessor.pl from submodule, that already is updated.

**Comment by sharp** [comment]
cp `gas-preprocessor.pl` to `/usr/local/bin` , Good luck

**Comment by kolyvan** [comment]
> Hey, thank you for the update. When I update kxmovie I got an error trying to run it in simulator:
> Undefined symbols for architecture i386:
> "_iconv", referenced from:
> _avcodec_decode_subtitle2 in libavcodec.a(utils.o)

Hm, looks like there is lack of libiconv.dylib.
But I added libiconv to the project in 7b77b0fa869e6fb3138458e3dddb27cf668acebd commit.

**Comment by aleufms** [comment]
Thanks guys. The errors is gone.
The error with iconv references is because I don't added libiconv to my project. The error with the actual device is because I don't put the new gas-preprocessor.pl to the /usr/bin.

The interruptCallback is working fine here.
