### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by jinan829** [kolyvan/kxmovie#4]
Hello kolyvan.
I am developing RTSP streaming player application using ffmpeg.
Your project is very similar with my idea.
But, when i build the application, i get the link error.

Ld /Users/wyp/Library/Developer/Xcode/DerivedData/kxmovie-dkcmadoxemowdgfmfnoqftidnwwm/Build/Products/Debug-iphonesimulator/KxMovieExample.app/KxMovieExample normal i386
    cd /Users/wyp/Downloads/kxmovie-master
    setenv IPHONEOS_DEPLOYMENT_TARGET 5.1
    setenv PATH "/Volumes/MAC_DATA/develop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Volumes/MAC_DATA/develop/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Volumes/MAC_DATA/develop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Volumes/MAC_DATA/develop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk -L/Users/wyp/Library/Developer/Xcode/DerivedData/kxmovie-dkcmadoxemowdgfmfnoqftidnwwm/Build/Products/Debug-iphonesimulator -L/Users/wyp/Downloads/kxmovie-master/libs -L/Users/wyp/Downloads/kxmovie-master -F/Users/wyp/Library/Developer/Xcode/DerivedData/kxmovie-dkcmadoxemowdgfmfnoqftidnwwm/Build/Products/Debug-iphonesimulator -F/Volumes/MAC_DATA/develop/Xcode.app/Contents/Developer/Library/Frameworks -filelist /Users/wyp/Library/Developer/Xcode/DerivedData/kxmovie-dkcmadoxemowdgfmfnoqftidnwwm/Build/Intermediates/kxmovie.build/Debug-iphonesimulator/KxMovieExample.build/Objects-normal/i386/KxMovieExample.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.1 -framework Foundation -framework UIKit -framework CoreGraphics -lz -lavcodec -lavdevice -lavformat -lavutil -lswresample -lswscale -framework MediaPlayer -framework CoreAudio -framework AudioToolbox -framework Accelerate -framework QuartzCore -framework OpenGLES -lkxmovie -o /Users/wyp/Library/Developer/Xcode/DerivedData/kxmovie-dkcmadoxemowdgfmfnoqftidnwwm/Build/Products/Debug-iphonesimulator/KxMovieExample.app/KxMovieExample

Undefined symbols for architecture i386:
  "_BZ2_bzDecompress", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressEnd", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressInit", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I hope you to help me.
Could you please tell me the issue?
Regards.

**Comment by sharp** [comment]
You need run 'rake' first, rake is one ruby script

**Comment by kolyvan** [comment]
Maybe you removed  '--disable-bzlib' in rake file ?

**Comment by jinan829** [comment]
It worked for me.
Thanks for your help.
