### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by flashlizi** [kolyvan/kxmovie#41]
Hi, I got these error when build kxmovie:

Executing cd ffmpeg; ./configure --disable-ffmpeg --disable-ffplay --disable-ffserver --disable-ffprobe --disable-doc --disable-bzlib --target-os=darwin --enable-cross-compile --enable-gpl --enable-version3 --arch=arm --cpu=cortex-a8 --enable-pic --extra-cflags='-arch armv7' --extra-ldflags='-arch armv7' --extra-cflags='-mfpu=neon -mfloat-abi=softfp -mvectorize-with-neon-quad' --enable-neon --enable-optimizations --disable-debug --disable-armv5te --disable-armv6 --disable-armv6t2 --enable-small --cc=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='gas-preprocessor.pl /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk --extra-ldflags=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/lib/system
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc is unable to create an executable file.
C compiler test failed.

---

mac os x lion 10.7.5
xcode 4.6.1

**Comment by flashlizi** [comment]
I found the errors in config.log:

check_ld cc
check_cc
BEGIN /var/folders/kf/__q_f1n9789cl9thm45p4fvw0000gn/T//ffconf.PBbHRq4i.c
    1   int main(void){ return 0; }
END /var/folders/kf/__q_f1n9789cl9thm45p4fvw0000gn/T//ffconf.PBbHRq4i.c
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -arch armv7 -mfpu=neon -mfloat-abi=softfp -mvectorize-with-neon-quad -mcpu=cortex-a8 -c -o /var/folders/kf/__q_f1n9789cl9thm45p4fvw0000gn/T//ffconf.almDZOMo.o /var/folders/kf/__q_f1n9789cl9thm45p4fvw0000gn/T//ffconf.PBbHRq4i.c
cc1: error: /Developer/usr/llvm-gcc-4.2/lib/gcc/arm-apple-darwin10/4.2.1/include: Not a directory
C compiler test failed.

How to fix this? thanks.

**Comment by kolyvan** [comment]
Hi,

Do you use a original Rakefile for build?
Just in case, I ran the build from scratch and  did not met any errors.

> cc1: error: /Developer/usr/llvm-gcc-4.2/lib/gcc/arm-apple-darwin10/4.2.1/include: Not a directory

Certainly, it's absolutly incorrect path. Valid is:

```
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/lib/gcc/arm-apple-darwin10/4.2.1/include
```

Best wishes

**Comment by flashlizi** [comment]
I've tried use iPhoneOS5.1.sdk to build, but failed. and i tried other solutions on stackoverflow but all failed.  
so I upadte my xcode to new 4.6.1 and rebuild it with original build rake file, failed again.
I also don't know why has this error:

```
cc1: error: /Developer/usr/llvm-gcc-4.2/lib/gcc/arm-apple-darwin10/4.2.1/include: Not a directory
```

 maybe because of cache? how can i do? thanks in advance.
