### ISSUE TITLE
Build for iOS device failed, while simulator worked

### ISSUE THREAD

**Issue by rollpard** [kolyvan/kxmovie#44]
![ 4U1K2FPDPW7 L 39Z8 FF8](https://f.cloud.github.com/assets/2740090/361295/62edef2a-a1bf-11e2-9d78-f11ec7c299ef.jpg)
I got this problem when build the KxmovieExample for iPhone4( ios6.1.2) and iPad2 (iOS 5.1.1), while the simulator worked well.
I follow the reame.md instruction to build it.
(1)get the source code by 
git clone git://github.com/kolyvan/kxmovie.git
(2)and then
cd kxmovie
git submodule update --init 
rake
the rake command succeed, but when I open the xCode project, build for the iOS device, the problem occurs.

**Comment by kolyvan** [comment]
HI,
Need update gas-preprocessor.pl to the version included as submodule into kxmovie project. 
Best wishes.

**Comment by kolyvan** [comment]
Please, check your gas-preprocessor.pl again

```
md5 /usr/bin/gas-preprocessor.pl 
MD5 (/usr/bin/gas-preprocessor.pl) = bbf7ae8dd66476d5bf823d8d8dc7474e
```

**Comment by kolyvan** [comment]
If gas-preprocessor.pl is valid file, then I unsure how I can help you, sorry.
