### ISSUE TITLE
Error while building when kxmovie is added to my project

### ISSUE THREAD

**Issue by bitsdisasters** [kolyvan/kxmovie#45]
Hi,

I am using Xcode Version 4.6 (4H127), iOS SDK 6.1 deploying target 6.0 and I was able to build kxmovie and its example after some trouble. I have  included kxmovie library from output folder and ffmpeg libs from libs one  and needed frameworks aswel to my own project but the build fails with the following errors (same errors on iPhone and simulator either):

![Screen Shot 2013-04-12 at 15 36 16](https://f.cloud.github.com/assets/2891174/373114/03e79ad4-a378-11e2-9bdb-32f71f2d3b4a.png)

I am adding the same code (test purpose at this moment) as in the example

![Screen Shot 2013-04-12 at 15 51 48](https://f.cloud.github.com/assets/2891174/373117/2837e36c-a378-11e2-9635-f2a43a770683.png)

![Screen Shot 2013-04-12 at 16 01 03](https://f.cloud.github.com/assets/2891174/373196/4a0ef8a2-a37a-11e2-85fe-11407a299a26.png)

I am relatively a newbie programming in iOS and I have been not able to solve this problem yet. I have tried to replace ffmpeg libs with others built directly from ffmpeg source code but it didn't work neither.

Thank you in advance

**Comment by kolyvan** [comment]
Hi,

IMHO it is obvious, you forgot to add libkxmovie.a library for linking.

Best wishes.

**Comment by bitsdisasters** [comment]
Hi,

Thank you for you answer but, could you explain to me how must I do that?. Sorry but I am still really lost in some aspect working with Xcode and Cocoa.
Thank you

**Comment by sharp** [comment]
libkxmovie.a is the kxmovie library, if you do not want to do that, just copy the kxmovie folder to your project

**Comment by bitsdisasters** [comment]
hi, thank you for your feedback. I followed the steps but I forgot to add libkxmovie.a because I didn't see it. I just discover where it is and now it compiles without errors :D 

Thanks

**Comment by PascoCoder** [comment]
where is the libkxmovie.a file ???
