### ISSUE TITLE
The player can not return back when decode video error

### ISSUE THREAD

**Issue by sharp** [kolyvan/kxmovie#5]
If the video is broken , the player  is still loading, it can not stop and go back, even if I click done button.

```
 decode video error, skip packet
[h264 @ 0xa209600] AVC: nal size 423386319
[h264 @ 0xa209600] AVC: nal size 423386319
[h264 @ 0xa209600] no frame!

```

![](http://i.imgur.com/hdHua.png)

**Comment by kolyvan** [comment]
Sorry, but I unable to reproduce this bug.
Perhaps You can give me the link to such broken video for checking the issue ?

**Comment by sharp** [comment]
Hi   kolyvan , one more question ,  my ipad will lock screen when playing , but MPMoviePlayer dose not lock screen

**Comment by kolyvan** [comment]
Hm, What do you mean 'my ipad will lock screen' ?

**Comment by sharp** [comment]
Right.  I open one video and do not touch the screen, the player will be not active after 120 seconds because the iPad lock the screen .

If I play video with full screen mode ,  there is no problem , so is there any way to play the video in full screen at first ?

**Comment by sharp** [comment]
I think it's better that the player will be full screen automatically after 10 seconds

**Comment by kolyvan** [comment]
Yes, you are correct. 
I call [UIApplication setIdleTimerDisabled: YES] only in fullscreen mode. 
You  may change this behaviour, by disabling the idle timer in viewWillApper: for example.

**Comment by sharp** [comment]
It works! thanks for your great job.
