### ISSUE TITLE
Playing video from NSInputStream

### ISSUE THREAD

**Issue by lukaszspaczynski** [kolyvan/kxmovie#54]
Hi, 

at first - grat job! kxmovie is amazing :)

I have a backend server that i connect via NSInputStream and NSOutputStream. When i send some controll msg via output stream, server start sending to me data (mp4 stream) via inpuput stream.

I have no idea how to connect ffmpeg with those data (NSInputStream), can You help?

**Comment by lukaszspaczynski** [comment]
solution:

const int ioBufferSize = 32768;
    unsigned char _ioBuffer = (unsigned char *)av_malloc(ioBufferSize + FF_INPUT_BUFFER_PADDING_SIZE);
    formatCtx->pb = avio_alloc_context(ioBuffer, ioBufferSize, 0, (__bridge void_)(stream), &readFromNSInputStreamFunction, NULL, NULL);
    formatCtx->pb->seekable = 0;
    formatCtx->pb->write_flag = 0;

```
if (avformat_open_input(&formatCtx, [@"fake" cStringUsingEncoding: NSUTF8StringEncoding], NULL, NULL) < 0) {

    if (formatCtx)
        avformat_free_context(formatCtx);
    return kxMovieErrorOpenStream;
}
```

where stream is NSInputStream object and readFromNSInputStreamFunction is:

static int readFromNSInputStreamFunction(void\* opaque, uint8_t\* buf, int buf_size) {
    __unsafe_unretained NSInputStream *stream = (__bridge NSInputStream *)opaque;

```
int numBytes = [stream read: (char*)buf maxLength: buf_size];

return numBytes;
```

}

**Comment by amansharma2014** [comment]
(__bridge void)(stream) gives error  passing void to parameter of incompatible type*
