### ISSUE TITLE
avpicture_deinterlace is deprecated 

### ISSUE THREAD

**Issue by su0f** [kolyvan/kxmovie#58]
I have this warning in KxMovieDecoder and it's causing a problem in loading film process can you help please

the problem is : when video start streaming sometimes it loads the audio before the video so I used to rotate the device in order to see the video again

**Comment by twoputt** [comment]
This issue was discussed and solved in:
    https://stackoverflow.com/questions/30614302/c-ffmpeg-yadif-deinterlacing
