### ISSUE TITLE
how to play live stream ?

### ISSUE THREAD

**Issue by sharp** [kolyvan/kxmovie#6]
I have one live stream,  the player can not stop. If application resign active, the player is pause, so the player can not go on playing when application active again

**Comment by sharp** [comment]
If I can reload the video by the path again, it will be happy :)

**Comment by kolyvan** [comment]
There are several ways to do this.
1. You can remove the handling for UIApplicationWillResignActiveNotification (applicationWillResignActive: method in KxMovieViewController).
   or
2. You can add the observation for  UIApplicationDidBecomeActiveNotification and resume play by it.

**Comment by jinan829** [comment]
Hello, SharpX
I am getting Lip sync issue from kxmovie player.
Have you ever got such issue?
Do you have any idea for it?
Regards.

**Comment by sharp** [comment]
Hi，What is " Lip sync" ? What's your media format  ?

It works well for me

**Comment by jinan829** [comment]
Hello, SharpX
Thanks for your reply.
Did you play video on your iPad?
It works well on iPhone.
If you play it on your iPad, you will notice it.
Best Regards.

**Comment by sharp** [comment]
You are "中国人" ?

**Comment by jinan829** [comment]
yes
Have you had a chance to look at the issue?
