### ISSUE TITLE
FFMpeg link error

### ISSUE THREAD

**Issue by jinan829** [kolyvan/kxmovie#7]
Hello
I put "-all_load" in "Other linker flags" option in Build settings.
Unfortunately, i am getting the following link error.
Could you please tell me any ideas for it?

Undefined symbols for architecture i386:
  "_av_abuffersink_params_alloc", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_av_buffersink_get_buffer_ref", referenced from:
      _lavfi_read_packet in libavdevice.a(lavfi.o)
  "_av_buffersink_params_alloc", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_get_by_name", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_alloc", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_config", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_create_filter", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_dump", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_free", referenced from:
      _lavfi_read_close in libavdevice.a(lavfi.o)
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_graph_parse", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_inout_free", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_link", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_register_all", referenced from:
      _lavfi_read_header in libavdevice.a(lavfi.o)
  "_avfilter_unref_buffer", referenced from:
      _lavfi_read_packet in libavdevice.a(lavfi.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I need your help.
Best Regards.

**Comment by kolyvan** [comment]
Maybe you can use –force_load flag instead of -all_load ?

**Comment by jinan829** [comment]
Thank you.
I solved it with -ObjC
Best Regards.
