### ISSUE TITLE
Lip sync

### ISSUE THREAD

**Issue by jinan829** [kolyvan/kxmovie#8]
Hello, Kolyvan

How are you?
I played Mpeg-4 h.264 video using kxmovie video player.
When i tried it on iPhone, it works great.
But, when i tried it on iPad, lip sync was terribly out.
They didn't really match.
Do you have any ideas for it?
I need your help.

Best Regards.

**Comment by jinan829** [comment]
Hello, Kolyvan
Have you had a chance to look at this issue?
I hope you to check the issue and tell me the solution.
Best Regards.

**Comment by sharp** [comment]
I think I have the same problem after some test

**Comment by kolyvan** [comment]
This issue is iPad only problem?
Sorry, but I can't help you with it now.
I tested kxmovie code only on iPhone.
Perhaps in the early january, I will be able to check kxmovie on iPad.

**Comment by jinan829** [comment]
Hello, Kolyvan.
Thanks for your checking.
I hope you to check the issue and fix it quickly.
You can also check it on the simulator.
Are you really busy?
Regards.

**Comment by jinan829** [comment]
One more question
Could you please tell me what will be the issue?
Then, i will be very thank you.
Regards.

**Comment by kolyvan** [comment]
I don't know where is a problem since I can't reproduce it so far.
It will be nice if you can add link to the sample movie which causes 'lip issue'.
Best wishes.

**Comment by jinan829** [comment]
Hello, Kolyvan.
Please test it on your iPad.
Especially, if you rotate it to landscape, it will work very slowly.
Regards.
