### ISSUE TITLE
Audio spectrum

### ISSUE THREAD

**Issue by aleufms** [kolyvan/kxmovie#9]
I'm using your example to stream audio and it worked. Is there a way to display audio spectrum instead static image? Thanks in advance.

**Comment by kolyvan** [comment]
Hi,
I just created new branch https://github.com/kolyvan/kxmovie/tree/spectrum and pushed commit: https://github.com/kolyvan/kxmovie/commit/2485f79231a857dad47fb15fc81ed1d9ed04285d with sample of rendering the audio spectrum.

![spectrum](https://f.cloud.github.com/assets/791320/21701/485e2ca0-49c8-11e2-85d6-33fa482904c8.png)

You can hack it if you need more.
Best wiches.

**Comment by sharp** [comment]
@kolyvan , Good job!  I just want to know is it possible to play RTMP stream ?

**Comment by kolyvan** [comment]
Yes, since kxmovie based on ffmpeg, and ffmpeg supports rtmp streaming.

**Comment by kolyvan** [comment]
ffmpeg reports

> TCP connection to livertmp.wasu.cn:1935 failed: Connection refused

And by request http://livertmp.wasu.cn/ server returns page with 'access denied'.
Maybe some server-side problems.
